server:
  port: 8000
  
spring:
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  application:
    name: ToolsKit-server
#    数据源
  datasource:
    url: jdbc:mysql://localhost:3306/vitea?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#    RebbitMq
  rabbitmq:
    host: 172.0.0.1
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        max-concurrency: 10
        concurrency: 10
      direct:
        prefetch: 10
    virtual-host: /
    publisher-confirms: true
    #    redis
  redis:
    host: 172.0.0.1
#    password: 123456
    port: 6379
    timeout: 6000
    database: 1
    lettuce:
      pool:
        max-active: 10 # 连接池最大连接数（使用负值表示没有限制）,如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
        max-idle: 8   # 连接池中的最大空闲连接 ，默认值也是8
        max-wait: 100 # # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException  
        min-idle: 2    # 连接池中的最小空闲连接 ，默认值也是0
      shutdown-timeout: 100ms

#mybatis-plus:
#  global-config:
#    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#    db-config:
#      id-type: auto
#  mapper-locations: classpath:/mapper/**/*.xml

    

