spring:
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  application:
    name: ToolsKit-RabbitMQ
  #    数据源
  datasource:
    url: jdbc:mysql://localhost:3306/vitea?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    #    host: 127.0.0.1
    host: 192.168.159.138
    port: 5672
    username: admin
    password: admin
    #    并发量的配置 并发消费者的初始化值，并发消费者的最大值，每个消费者每次监听时可拉取处理的消息数量。
    listener:
      simple:
        max-concurrency: 20
        concurrency: 10
      direct:
        prefetch: 5
    virtual-host: /
    publisher-confirms: true
  redis:
  #    host: 127.0.0.1
    host: 192.168.159.138
    password: admin
    port: 6379
    timeout: 6000
    database: 1
    lettuce:
      pool:
        max-active: 10 # 连接池最大连接数（使用负值表示没有限制）,如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
        max-idle: 8   # 连接池中的最大空闲连接 ，默认值也是8
        max-wait: 100 # # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
        min-idle: 2    # 连接池中的最小空闲连接 ，默认值也是0
      shutdown-timeout: 100ms

server:
  port: 19002
